name: tests

on:
  pull_request

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2 #take all the code to our project
     - run: cd auth && npm install && npm run test:ci
